name: grad
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.2



  cupertino_icons: ^1.0.6
  fl_chart: ^0.69.0
  lottie: ^3.1.3
  convert: ^3.0.0
  flutter_blue_plus: ^1.4.0
  shared_preferences: ^2.3.2
  mailer: ^6.2.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.4
  tflite_flutter: ^0.11.0


  get: ^4.6.6
  permission_handler: ^11.2.0
  url_launcher: ^6.2.4

  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/glooko.png
    - assets/glucoselvlpng.png
    - assets/insulin.png
    - assets/carbs.png
    - assets/diabetes.png
    - assets/glookonew.json
    - assets/glookogif.gif
    - assets/google.png
    - assets/back.png
    - assets/calories.png
    - assets/heart-rate.png
    - assets/blood-pressure.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
